'use server'

import { Client } from '@microsoft/microsoft-graph-client'
import { ConfidentialClientApplication } from '@azure/msal-node'

// Constants for Graph API Auth
const TENANT_ID = process.env.MS_GRAPH_TENANT_ID || ''
const CLIENT_ID = process.env.MS_GRAPH_CLIENT_ID || ''
const CLIENT_SECRET = process.env.MS_GRAPH_CLIENT_SECRET || ''
const SHARED_MAILBOX = process.env.MS_GRAPH_SHARED_MAILBOX || ''

/**
 * Helper to initialize the Microsoft Graph Client using MSAL Node.
 */
async function getGraphClient() {
    if (!TENANT_ID || !CLIENT_ID || !CLIENT_SECRET) {
        throw new Error("Microsoft Graph API credentials are not fully configured in your environment.")
    }

    const msalConfig = {
        auth: {
            clientId: CLIENT_ID,
            authority: `https://login.microsoftonline.com/${TENANT_ID}`,
            clientSecret: CLIENT_SECRET,
        }
    }

    const cca = new ConfidentialClientApplication(msalConfig)

    const authProvider = async (callback: (error: any, accessToken: string | null) => void) => {
        try {
            const authResponse = await cca.acquireTokenByClientCredential({
                scopes: ['https://graph.microsoft.com/.default']
            })
            callback(null, authResponse?.accessToken || null)
        } catch (error) {
            callback(error, null)
        }
    }

    return Client.init({
        authProvider
    })
}

/**
 * Sends a notification directly to the Shared Mailbox when a supplier submits a new quote.
 */
export async function notifySharedMailbox(quoteData: any): Promise<{ success: boolean, error?: string }> {
    try {
        if (!SHARED_MAILBOX) {
            console.warn("MS_GRAPH_SHARED_MAILBOX is not configured. Skipping internal notification.")
            return { success: false, error: "MS_GRAPH_SHARED_MAILBOX not configured" }
        }

        const client = await getGraphClient()

        // Use the shared mailbox to send an email to ITSELF so the team gets notified
        const mail = {
            message: {
                subject: `New Supplier Quote Submitted - ${quoteData.companyName || 'Unknown'}`,
                body: {
                    contentType: 'HTML',
                    content: `
                        <h2>A new quote has been submitted!</h2>
                        <p><strong>Company:</strong> ${quoteData.companyName}</p>
                        <p><strong>Email:</strong> ${quoteData.email}</p>
                        <p><strong>Pricing:</strong> ${quoteData.pricing}</p>
                        <p><strong>Lead Time:</strong> ${quoteData.leadTime}</p>
                        <p><strong>Notes:</strong> ${quoteData.notes || 'N/A'}</p>
                        <br/>
                        <p>Log in to the system to review and approve this quote.</p>
                    `
                },
                toRecipients: [
                    { emailAddress: { address: SHARED_MAILBOX } }
                ]
            },
            saveToSentItems: 'false' // Don't clog sent items for internal ping
        }

        await client.api(`/users/${SHARED_MAILBOX}/sendMail`).post(mail)
        return { success: true }
    } catch (e: any) {
        console.error("notifySharedMailbox error:", e)
        return { success: false, error: e.message }
    }
}

/**
 * Returns a static bilingual template (Latvian/English) for approving the quote.
 */
export async function generateConfirmationEmail(quoteData: any): Promise<string> {
    const company = quoteData.companyName || 'Supplier'

    return `Cienījamais ${company},

Ar šo apstiprinām Jūsu iesniegto piedāvājumu. Pielikumā atradīsiet sagatavoto Pirkuma Pasūtījumu (PO).
Lūdzu, ņemiet vērā, ka piegādes laiks un cena saskan ar Jūsu norādīto informāciju.

Paldies par sadarbību!

---

Dear ${company},

We hereby accept your submitted quote. Attached you will find the generated Purchase Order (PO).
Please note that the lead time and pricing match your provided information.

Thank you for your cooperation!`
}

/**
 * Dispatches an approved email text to the supplier directly from the Shared Mailbox.
 * Includes an optional PDF attachment (passed as base64 from the client renderer).
 */
export async function sendSupplierConfirmation(
    toEmail: string,
    subject: string,
    body: string,
    attachmentBase64?: string
): Promise<{ success: boolean, error?: string }> {
    try {
        if (!SHARED_MAILBOX) throw new Error("MS_GRAPH_SHARED_MAILBOX is missing.")
        if (!toEmail) throw new Error("Supplier email is missing.")

        const client = await getGraphClient()

        const attachments = []

        // If a PDF was generated by the client, attach it to the email payload
        if (attachmentBase64) {
            // Strip data:application/pdf;base64, prefix if present
            const cleanBase64 = attachmentBase64.replace(/^data:application\/pdf;base64,/, '')
            attachments.push({
                "@odata.type": "#microsoft.graph.fileAttachment",
                "name": "Purchase_Order.pdf",
                "contentType": "application/pdf",
                "contentBytes": cleanBase64
            })
        }

        const mail = {
            message: {
                subject: subject,
                body: {
                    // Send as text or HTML based on presence of tags. Using basic TEXT for physical typed letters.
                    contentType: 'Text',
                    content: body
                },
                toRecipients: [
                    { emailAddress: { address: toEmail } }
                ],
                attachments: attachments.length > 0 ? attachments : undefined
            },
            saveToSentItems: 'true' // Save to the Shared Mailbox's sent items so everyone can see it was dispatched
        }

        await client.api(`/users/${SHARED_MAILBOX}/sendMail`).post(mail)
        return { success: true }
    } catch (e: any) {
        console.error("sendSupplierConfirmation error:", e)
        return { success: false, error: e.message }
    }
}
